
```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(xtable)
library(gsubfn)
library(fmtr)
library(stringr)
library(common)
library(proto)
library(patchwork)
library(scales)
library(xtable)
library(ggthemes)
library(psych)

# CC=clang 
# CXX=clang++
# CXX98=clang++
# CXX11=clang++
# CXX14=clang++
# CXX17=clang++

theme_set(theme_light())
"%!in%" <- function(x, y) !("%in%"(x, y))

# options(scipen = 999)
# options(digits = 5, nsmall = 3)

options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

Generate insert table

```{r}
# setwd("/home/zmen002/KDtree")
precesion=2
df <- read.csv("script/data/result.csv",header=TRUE)
df <- df %>% filter(dims==3)


df <- df %>% group_by(solver,benchType,nodes,dims)%>% 
  summarise(across(-file,mean),.groups="drop") %>%
  select(solver,benchType,nodes,dims,build,insert,delete) %>%
  pivot_wider(buildDatanames_from=solver,values_from=c(build,insert,delete)) %>% 
  rowwise() %>%
  mutate(min_build=min(build_cgal,build_test,build_zdtree),
    min_insert=min(insert_cgal,insert_test,insert_zdtree),
    min_delete=min(delete_cgal,delete_test,delete_zdtree),
  ) 

geoMeans <- df %>% ungroup %>% 
  summarise_at(vars(-benchType,-nodes,-dims),geometric.mean) %>%
  apply(1,function(x) paste0("&",round(x,precesion))) 
# apply(1,paste,collapse=" ") %>%
geoMeans <- paste(geoMeans[1:9], collapse=" ")
geoMeans

df[4:6]<- lapply(df[4:6],function(x) ifelse(x==df$min_build, paste0("\\underline{",round(x,precesion),"}"), round(x,precesion)))
df[7:9]<- lapply(df[7:9],function(x) ifelse(x==df$min_insert, paste0("\\underline{",round(x,precesion),"}"), round(x,precesion)))
df[10:12]<- lapply(df[10:12],function(x) ifelse(x==df$min_delete, paste0("\\underline{",round(x,precesion),"}"), round(x,precesion)))

df <- df[1:12]

View(df)

#* begin table
df[[1]]
rle.lengths <- rle(df[[1]])$lengths
rle.lengths
first <- !duplicated(df[[1]])
df[[1]][!first] <- ""

# define appearance of \multirow
df[[1]][first] <-
paste0("\\midrule\\multirow{", rle.lengths, "}{*}{\\textbf{", df[[1]][first], "}}")

View(df)
# set up xtable output
print(xtable(df, 
  align = "lc|cc|ccc|ccc|ccc",  # align and put a vertical line (first "l" again represents column of row numbers)
  caption = paste0("\\textbf{Build and batch update table}"), label = "buildTable"),
  size = "normalsize", #Change size; useful for bigger tables "normalsize" "footnotesize"
  include.rownames = FALSE, #Don't print rownames
  include.colnames = FALSE, #We create them ourselves
  caption.placement = "top", #"top", NULL
  hline.after=NULL, #We don't need hline; we use booktabs
  floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
  sanitize.text.function = force, # Important to treat content of first column as latex function
  add.to.row = list(pos = list(-1,
    nrow(df)),
    command = c(paste("\\toprule \n",  # NEW row
      "\\multicolumn{1}{c}{} & \\multicolumn{2}{c}{\\textbf{Parameters}} & \\multicolumn{3}{c}{\\textbf{Build}} & \\multicolumn{3}{c}{\\textbf{Insert}}& \\multicolumn{3}{c}{\\textbf{Delete}} \\\\\n",
      " & Nodes & Dim  & CGAL & Ours & Zdtree & CGAL & Ours & Zdtree & CGAL & Ours & Zdtree \\\\\n" # NEW row 
    ),
      paste("\\midrule \n",
        "\\multicolumn{1}{c}{} & \\multicolumn{2}{c|}{\\textbf{Geometric Mean}}",
        geoMeans,
        "\\\\\n",
        "\\bottomrule \n"
      )
    )
  ),
  booktabs=TRUE
)
```

Generate query table

```{R}
df <- read.csv("script/data/result.csv",header=TRUE)
df <- df %>% filter(dims==3)

# View(df)

df <- df %>% group_by(solver,benchType,nodes,dims)%>% 
summarise(across(-file,mean),.groups="drop") %>%
select(solver,benchType,nodes,dims,queryTime,rangeCountTime,rangeQueryTime) %>%
pivot_wider(names_from=solver,values_from=c(queryTime,rangeCountTime,rangeQueryTime)) %>% 
rowwise() %>%
mutate(min_query=min(queryTime_cgal,queryTime_test,queryTime_zdtree),
min_count=min(rangeCountTime_cgal,rangeCountTime_test,rangeCountTime_zdtree),
min_range=min(rangeQueryTime_cgal,rangeQueryTime_test,rangeQueryTime_zdtree),
) 

df[4:6]<- lapply(df[4:6],function(x) ifelse(x==df$min_query, paste0("\\underline{",round(x,3),"}"), round(x,3)))
df[7:9]<- lapply(df[7:9],function(x) ifelse(x==df$min_count, paste0("\\underline{",round(x,3),"}"), round(x,3)))
df[10:12]<- lapply(df[10:12],function(x) ifelse(x==df$min_range, paste0("\\underline{",round(x,3),"}"), round(x,3)))
df <- df[1:12]

geoMeans <- df %>% ungroup %>% 
summarise_at(vars(-benchType,-nodes,-dims),geometric.mean) %>%
apply(1,function(x) paste0("&",round(x,precesion))) 
# apply(1,paste,collapse=" ") %>%
geoMeans <- paste(geoMeans[1:9], collapse=" ")

View(df)

df[[1]]
rle.lengths <- rle(df[[1]])$lengths
rle.lengths
first <- !duplicated(df[[1]])
df[[1]][!first] <- ""
# View(df)

# define appearance of \multirow
df[[1]][first] <-
paste0("\\midrule\\multirow{", rle.lengths, "}{*}{\\textbf{", df[[1]][first], "}}")


# set up xtable output
print(xtable(df, 
align = "lc|cc|ccc|ccc|ccc",  # align and put a vertical line (first "l" again represents column of row numbers)
caption = paste0("\\textbf{Query table}"), label = "queryTable"),
size = "normalsize", #Change size; useful for bigger tables "normalsize" "footnotesize"
include.rownames = FALSE, #Don't print rownames
include.colnames = FALSE, #We create them ourselves
caption.placement = "top", #"top", NULL
hline.after=NULL, #We don't need hline; we use booktabs
floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
sanitize.text.function = force, # Important to treat content of first column as latex function
add.to.row = list(pos = list(-1,
nrow(df)),
command = c(paste("\\toprule \n",  # NEW row
"\\multicolumn{1}{c}{} & \\multicolumn{2}{c}{\\textbf{Parameters}} & \\multicolumn{3}{c}{\\textbf{KNN}} & \\multicolumn{3}{c}{\\textbf{Range Count}}& \\multicolumn{3}{c}{\\textbf{Range Query}} \\\\\n",
" & Nodes & Dim  & CGAL & Ours & Zdtree & CGAL & Ours & Zdtree & CGAL & Ours & Zdtree \\\\\n" # NEW row 
),
paste("\\midrule \n",
"\\multicolumn{1}{c}{} & \\multicolumn{2}{c|}{\\textbf{Geometric Mean}}",
geoMeans,
"\\\\\n",
"\\bottomrule \n"
)
)
),
booktabs=TRUE
)
```
